const {
  UKMETOFFICEBASEURL,
  UKMETOFFICEAPPLICATIONCLIENTID,
  UKMETOFFICEAPPLICATIONCLIENTSECRET,
  UKMETOFFICEAPIGENERALORDERID,
  UKMETOFFICEAPIIVRORDERID,
  UKMETOFFICELOCALDIR,
  AGVISELYPORT,
  AGVISELYHOST,
  AGVISELYUSER,
  AGVISELYKEY,
  AGVISELYPATH,
  WBHOST,
  WBUSER,
  WBPASS,
  WBPATH,
  WBPATHLOCAL,
  MUNGBEANFILESDIR
} = process.env;

module.exports = {
  baseURLMetOffice: UKMETOFFICEBASEURL,
  clientIdMetOffice: UKMETOFFICEAPPLICATIONCLIENTID,
  clientSecretMetOffice: UKMETOFFICEAPPLICATIONCLIENTSECRET,
  apiOrderIdMetOfficeGeneral: UKMETOFFICEAPIGENERALORDERID,
  apiOrderIdMetOfficeIVR: UKMETOFFICEAPIIVRORDERID,
  pathLocalMetOffice: UKMETOFFICELOCALDIR,
  portAgvisely: AGVISELYPORT,
  hostAgvisely: AGVISELYHOST,
  userAgvisely: AGVISELYUSER,
  pathAgviselyKey: AGVISELYKEY,
  pathAgviselyOutput: AGVISELYPATH,
  hostWB: WBHOST,
  userWB: WBUSER,
  passWB: WBPASS,
  pathWB: WBPATH,
  pathLocalWB: WBPATHLOCAL,
  pathMungbean: MUNGBEANFILESDIR
};
